### ISSUE TITLE
ModuleNotFoundError: No module named 'gitdb.utils.compat'

### ISSUE THREAD

**Issue by ulidtko** [vgrabovets/benchmarkit#21]
Hi!

Nice package, I'm glad to report the first issue with it :)

`pip3 install benchmarkit` works just fine, however the package fails to import right after that:
```
...
Successfully installed GitPython-2.1.11 benchmarkit-0.0.3 colorama-0.4.1 gitdb-4.0.2 gitdb2-4.0.2 importlib-metadata-1.5.0 numpy-1.18.1 pandas-0.24.2 path.py-12.0.1 python-dateutil-2.8.1 pytz-2019.3 smmap-3.0.1 zipp-3.1.0
$ 
$ 
$ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import benchmarkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/benchmarkit/__init__.py", line 1, in <module>
    from benchmarkit.core import (  # noqa
  File "/usr/local/lib/python3.7/dist-packages/benchmarkit/core.py", line 11, in <module>
    from git import InvalidGitRepositoryError, Repo
  File "/usr/local/lib/python3.7/dist-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/usr/local/lib/python3.7/dist-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/usr/local/lib/python3.7/dist-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
```

BTW, this exact same error is why Travis isn't green. :negative_squared_cross_mark: 

This is the cause: gitpython-developers/GitPython#983 ... some rather sloppy version management.

The fix is to bump the GitPython dependency, to `2.1.15` (or better yet, migrate to `3.0.8` since you already have `python_requires='>=3.6.0'`). PR incoming.

**Comment by vgrabovets** [comment]
Thank you for fixing it!
I don't understand why I wasn't notified by travis that cron jobs had been failing for 3 weeks.
